name: Trivy

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REPOSITORY: ascheid/security-tools
  REGISTRY: sentinel #127893201980.dkr.ecr.ca-central-1.amazonaws.com/scan-files

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Build container
        working-directory: ./images/cloud_asset_inventory/sentinel_neo4j_forwarder
        run: |
          docker build \
            --build-arg git_sha=$GITHUB_SHA \
            -t $REGISTRY/sentinel:$GITHUB_SHA \
            -t $REGISTRY/sentinel:latest .
      
      - name: install trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.34.0
        
      - name: run trivy docker
        run: |
          trivy image \
          --format github \
          --vuln-type os,library \
          --severity UNKNOW,LOW,MEDIUM,HIGH,CRITICAL \
          --output dependency-results.sbom.json $REGISTRY/sentinel

      - name: replace apk with alpine
        run: |
          sed -i 's/pkg:apk/pkg:alpine/g' dependency-results.sbom.json
          cat dependency-results.sbom.json
          
      - name: upload results
        run: |
          curl -H 'Accept: application/vnd.github+json' -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" 'https://api.github.com/repos/'$GITHUB_REPOSITORY'/dependency-graph/snapshots' -d dependency-results.sbom.json

